### ISSUE TITLE
Baseline styles don't seem to be injected

### ISSUE THREAD

**Issue by antoniojps** [zeit-ui/react#218]
# About `styles` 🛠️

Hey 👋 - I'm setting up this library for a Next.js project and I followed the [Server Render](https://react.zeit-ui.co/en-us/guide/server-render) documentation, this is the [`_document.tsx` I came up with](https://github.com/antoniojps/zeit-ui-next-repro/blob/master/pages/_document.tsx).

If I `console.log(styles)` the styles it's an empty array.

After setting it up, the css baseline styles don't seem to be injected, specially the font-family.

The only component that I tested that had the correct styles was the button.
![Screenshot 2020-05-20 at 01 02 32](https://user-images.githubusercontent.com/19779828/82390076-9e6b5580-9a35-11ea-8afa-6fc168181409.png)

**Live example**: https://with-typescript-zeit-ui.antoniojps.now.sh/
**Reproduction** repository: https://github.com/antoniojps/zeit-ui-next-repro

**Comment by unix** [comment]
This is because `CssBaseline` is not injected into the Next application, this has nothing to do with server-side rendering. To use `zeit-ui/react` in any React appliacation, [you need to include the following statement](https://react.zeit-ui.co/en-us/guide/installation):

```jsx
const Application = () => (
  <ZeitProvider>      // ---> Base provider
    <CssBaseline />     // ---> normalize styles
    <AppComponent />    // ---> Your App Component
  </ZeitProvider>
)
```

For Next applications, you need to create and customize `_app.jsx` file, you can refer to the code [here](https://github.com/unix/unix.bio/blob/template/pages/_app.jsx).

I will then add some sample projects related to NextJS to  help users get started.

**Comment by antoniojps** [comment]
@unix Oh wow, I’m feeling so dumb right now. Long day of work 😅 thank you!
