### ISSUE TITLE
vertically offset modal -  reopening existing issue

### ISSUE THREAD

**Issue by bryanhpchiang** [zeit-ui/react#300]
just wanted to reopen this old issue from yesterday https://github.com/zeit-ui/react/issues/295

i just checked the official vercel implementation
https://vercel.com/design/modal

and it seems that the modal does remain vertically centered -- wondering if either default behavior can be changed or an option can be added. or add a note in docs indicating that behavior diverges from official implementation since top-aligned is a bit surprising

<img width="1680" alt="Screen Shot 2020-06-29 at 6 42 00 AM" src="https://user-images.githubusercontent.com/10623745/86013209-bee2e400-b9d3-11ea-8aea-0946b0038b23.png">

**Comment by unix** [comment]
First of all, I have to say that our implementation is **not exactly** the same as Vercel. We refer to some elements of the design draft, but not exactly the same. On the front page of the document, you can see "*originating from Vercel's design*", but I don't want to just make a complete replica. In fact, I optimized and improved every component,many new components have also been added, I want everyone to see the difference, instead of simply saying, "I checked something and what did you do wrong".

I will consider every opinion carefully, you can leave  the advantages and differences of your point of view and tell me waht you feel. I hope all issues are a kind of discussion and communication, not a censure.

However, it has to be admitted that when the height of `Modal` is very large, upward offset is not a good practice, it seems a little strange. (the purpose of this is to get better display when `Modal` is small.) I'll optimize this behavior in next release. 

And for everyone, if you find that your issue is closed, please please follow the `issue template` to reopen. (I will note this in template.) This will make it easier for others to search and view.

**Comment by bryanhpchiang** [comment]
got it, thanks for explaining. zeit-ui.co says "Here are some of our implementations of Vercel design". so i would expect the implementation to match the official design system. like if w3c released a spec, it would make sense for the implementations to match what was indicated in the original spec. 

obviously this is up to you in the end and nobody expects every pixel/frame to be the same, but if there are intentional, noticeable optimizations and deviations from the vercel design system then i feel it's appropriate for it to be noted in the docs / overview.

and i'll use the issue template in the future, thx for letting me know
