### ISSUE TITLE
Toast position configureable

### ISSUE THREAD

**Issue by hoetmaaiers** [zeit-ui/react#306]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

I would like the toast to be configurable in one of 4 screen corners. Is this on purpose not on option or just room for improvement?

**Comment by unix** [comment]
This is really something that can be improved, in fact, I considered and tried this idea when I created `Toast` component, and it's not hard to do this in code. But I finally removed this feature, because the animation effect is not satisfactory.

For example, the `Toast` component at the bottom are stacked together, they gradually move up and disappear, and there is a hierarchical relationship of the Z-axis, but if they're at the top, the opposite Z-axis relationship looks strange. (Note that all components need to be expanded when the mouse move-in.) The animation of component `Toast` looks good, but it doesn't work well in the opposite position.

**Comment by unix** [comment]
Remove stacked effects makes them look more reasonable (in `placement` case), but it's not a good idea either, so I finally removed `placement`.

**Comment by hoetmaaiers** [comment]
I do think the stacked effects are a good thing. The animations should be tailored to the position then I think.

Is it possible to render the toasts in a specific container element? This way, the position could be tweaked.

**Comment by unix** [comment]
Yes, it's in a container right now.
I mean the animation is form top to bottom, and stacking is also from top to bottom, which is very strange. Well, it's hard to explain, but what I'm saying is that this feature was removed for no technical reason.

**Comment by unix** [comment]
Hi, @hoetmaaiers , I create a new issue to extend your idea, this issue has been moved #315 .

**Comment by hoetmaaiers** [comment]
Thanks for digging further into this.
